# Generated by Django 3.0.8 on 2022-08-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menuuuid"),
        ("employees", "0002_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="comments",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("menu", "employee")},
        ),
    ]
