# Generated by Django 3.0.8 on 2022-08-10 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menuuuid"),
        ("employees", "0003_auto_20220810_0114"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="menu.Menu",
            ),
        ),
    ]
