# Generated by Django 3.0.8 on 2022-08-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_menuuuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuuuid",
            name="is_send",
            field=models.BooleanField(default=False),
        ),
    ]
